inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - gemfiles/vendor/**/*

# TODO(uwe): Remove after updating to rubocop 1.0
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
# ODOT

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/HeredocIndentation:
  EnforcedStyle: active_support

Layout/LineLength:
  Max: 107
  IgnoreCopDirectives: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Lint/Debugger:
  Enabled: false

# Offense count: 2
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

Security/Eval:
  Exclude:
    - gemfiles/*.gemfile

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
