inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - gemfiles/vendor/**/*
  NewCops: enable

#Layout/ArgumentAlignment:
#  EnforcedStyle: with_fixed_indentation
#  IndentationWidth: 4

Layout/HeredocIndentation:
  Enabled: true

Layout/LineLength:
  Max: 107
  IgnoreCopDirectives: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2


Lint/Debugger:
  Enabled: false

# Offense count: 2
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

Security/Eval:
  Exclude:
    - gemfiles/*.gemfile

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
